name: database-dev-env

services:
  workspace:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    init: true
    volumes:
      - type: bind
        source: .
        target: /workspace
    
  mysql:
    extends:
      file: mysql/docker-compose.yml
      service: mysql
    
  sqlserver:
    extends:
      file: sqlserver/docker-compose.yml
      service: sqlserver
    
  redis:
    extends:
      file: redis/docker-compose.yml
      service: redis

  phpmyadmin:
    extends:
      file: phpmyadmin/docker-compose.yml
      service: phpmyadmin

volumes:
  mysql_data:
    name: dev_mysql_data
  mysql_backup:
    name: dev_mysql_backup
  mysql_logs:
    name: dev_mysql_logs
  sqlserver_data:
    name: dev_sqlserver_data
  redis_data:
    name: dev_redis_data

networks:
  mysql-network:
    name: dev_mysql_network
  sqlserver-network:
    name: dev_sqlserver_network
  redis-network:
    name: dev_redis_network 