services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    platform: linux/arm64/v8
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-TedyDev@2310}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${MYSQL_DATABASE:-master}
      MYSQL_USER: ${MYSQL_USER:-sa}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-TedyDev@2310}
      TZ: ${TZ:-Asia/Ho_Chi_Minh}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./backups/mysql:/backup
      - ./logs/mysql:/var/log/mysql
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    command: 
      --authentication-policy=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --max_connections=${MYSQL_MAX_CONNECTIONS:-500}
      --wait_timeout=${MYSQL_WAIT_TIMEOUT:-1800}
      --innodb_buffer_pool_size=${MYSQL_BUFFER_POOL_SIZE:-512M}
      --innodb_log_file_size=128M
      --performance_schema=OFF
    networks:
      - mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: arm64v8/phpmyadmin:latest
    container_name: phpmyadmin-container
    restart: unless-stopped
    platform: linux/arm64/v8
    ports:
      - "${PMA_PORT:-8088}:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-TedyDev@2310}
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT:-64M}
      MAX_EXECUTION_TIME: ${PMA_MAX_EXECUTION_TIME:-300}
      MEMORY_LIMIT: ${PMA_MEMORY_LIMIT:-256M}
    volumes:
      - ./config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
      - ./logs/phpmyadmin:/var/log/php
    networks:
      - mysql-network
    depends_on:
      - mysql

  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    platform: linux/arm64/v8
    container_name: sqlserver-container
    restart: unless-stopped
    ports:
      - "${SQL_PORT:-1433}:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SQL_SA_PASSWORD:-TedyDev@2310}
      MSSQL_PID: "Developer"
      MSSQL_COLLATION: ${SQL_COLLATION:-Vietnamese_CI_AS}
      MSSQL_MEMORY_LIMIT_MB: ${SQL_SERVER_MAX_MEMORY:-4096}
      MSSQL_AGENT_ENABLED: "true"
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_LOG_DIR: /var/opt/mssql/log
      MSSQL_BACKUP_DIR: /var/opt/mssql/backup
      TZ: ${TZ:-Asia/Ho_Chi_Minh}
    volumes:
      - ./data/sqlserver:/var/opt/mssql
      - ./backups/sqlserver:/var/opt/mssql/backup
      - ./logs/sqlserver:/var/opt/mssql/log
    networks:
      - sqlserver-network
    cap_add:
      - SYS_PTRACE
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis:
    image: redis:latest
    container_name: redis-container
    restart: unless-stopped
    platform: linux/arm64/v8
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --save 60 1 --loglevel warning --maxmemory ${REDIS_MAX_MEMORY:-2gb} --maxmemory-policy allkeys-lru
    volumes:
      - ./data/redis:/data
      - ./logs/redis:/var/log/redis
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  mysql-network:
    name: mysql-network
  sqlserver-network:
    name: sqlserver-network
  redis-network:
    name: redis-network 