version: '3.8'

services:
      mysql:
            image: mysql:8.0
            container_name: mysql-container
            restart: unless-stopped
            platform: linux/arm64/v8
            ports:
                  - "3306:3306"
            networks:
                  - mysql-network
            environment:
                  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-TedyDev@2310}
                  MYSQL_ROOT_HOST: "%"
                  MYSQL_DATABASE: ${MYSQL_DATABASE:-master}
                  MYSQL_USER: ${MYSQL_USER:-sa}
                  MYSQL_PASSWORD: ${MYSQL_PASSWORD:-TedyDev@2310}
                  TZ: ${TZ:-Asia/Ho_Chi_Minh}
            volumes:
                  - mysql_data:/var/lib/mysql
                  - mysql_backup:/backup
                  - mysql_logs:/var/log/mysql 
            command: 
                  --authentication-policy=mysql_native_password
                  --character-set-server=utf8mb4
                  --collation-server=utf8mb4_unicode_ci
                  --max_connections=${MYSQL_MAX_CONNECTIONS:-500}
                  --wait_timeout=${MYSQL_WAIT_TIMEOUT:-1800}
                  --innodb_buffer_pool_size=${MYSQL_BUFFER_POOL_SIZE:-512M}
                  --innodb_log_file_size=128M
                  --performance_schema=OFF
            healthcheck:
                  test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
                  interval: 10s
                  timeout: 5s
                  retries: 3

networks:
      mysql-network:
            driver: bridge
            name: mysql-network

volumes:
      mysql_data:
            name: mysql_data 
      mysql_backup:
            name: mysql_backup
      mysql_logs:
            name: mysql_logs