version: '3.8'

services:
      sqlserver:
            image: mcr.microsoft.com/azure-sql-edge:latest
            platform: linux/arm64/v8
            container_name: sqlserver-container
            restart: unless-stopped
            ports:
                  - "${SQL_PORT:-1433}:1433"
            networks:
                  - sqlserver-network
            environment:
                  ACCEPT_EULA: "Y"
                  MSSQL_SA_PASSWORD: ${SQL_SA_PASSWORD:-TedyDev@2310}
                  MSSQL_PID: "Developer"
                  MSSQL_COLLATION: ${SQL_COLLATION:-Vietnamese_CI_AS}
                  MSSQL_MEMORY_LIMIT_MB: ${SQL_SERVER_MAX_MEMORY:-4096}
                  MSSQL_AGENT_ENABLED: "true"
                  MSSQL_DATA_DIR: /var/opt/mssql/data
                  MSSQL_LOG_DIR: /var/opt/mssql/log
                  MSSQL_BACKUP_DIR: /var/opt/mssql/backup
                  TZ: ${TZ:-Asia/Ho_Chi_Minh}
            volumes:
                  - sqlserver_data:/var/opt/mssql
                  - ./backup:/var/opt/mssql/backup
                  - ./logs:/var/opt/mssql/log
            cap_add:
                  - SYS_PTRACE
            healthcheck:
                  test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -Q "SELECT 1" || exit 1
                  interval: 10s
                  timeout: 5s
                  retries: 3
                  start_period: 10s

networks:
      sqlserver-network:
            driver: bridge
            name: sqlserver-network

volumes:
      sqlserver_data:
            name: sqlserver_data 